spring.application.name=backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/pg-spring-react-db
## Remember to change these credentials in production and use environment variables or a secrets manager
spring.datasource.username=admin
spring.datasource.password=verySecurePassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.show-sql=false
## Automatically create and drop the database schema on application startup and shutdown
## On production, use 'update' or 'validate' instead of 'create-drop'
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false

# Server Configuration
## In development, you can use the default port 8080.
## In production, consider using environment variables to set the port.
server.port=8080
## In production build, do not bind errors
spring.web.error.include-binding-errors=always
## Below settings are helpful for debugging in development, change to 'never' in production
spring.web.error.include-message=always
spring.web.error.include-stacktrace=always